# Generated by Django 5.0.6 on 2024-05-25 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Name")),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Surname"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Birth Date"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Release Date"
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stock")),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="books", to="books.author", verbose_name="Authors"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="books", to="books.genre", verbose_name="Genres"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Borrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrowed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Borrowed At"),
                ),
                ("due_date", models.DateTimeField(verbose_name="Due Date")),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Returned At"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrows",
                        to="books.book",
                        verbose_name="Book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrowed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Borrowed At"),
                ),
                ("due_date", models.DateTimeField(verbose_name="Due Date")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserves",
                        to="books.book",
                        verbose_name="Book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserves",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
