# Generated by Django 5.0.6 on 2024-05-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrow",
            name="returned",
            field=models.BooleanField(default=False, verbose_name="Returned"),
        ),
        migrations.AddField(
            model_name="reserve",
            name="status",
            field=models.BooleanField(
                db_default=False, default=False, verbose_name="Status"
            ),
        ),
    ]
